{% set version = "0.18.1" %}

package:
  name: cloog
  version: {{ version }}

source:
  fn: cloog-{{ version }}.tar.gz
  url: http://www.bastoul.net/cloog/pages/download/count.php3?url=./cloog-{{ version }}.tar.gz
  sha256: 02500a4edd14875f94fe84cbeda4290425cb0c1c2474c6f75d75a303d64b4196

build:
  number: 0
  skip: true    # [win]

requirements:
  build:
    - gmp 5.1.2
    - isl 0.12.2

  run:
    - gmp 5.1.2
    - isl 0.12.2

test:
  commands:
    - test -f "$PREFIX/lib/libcloog-isl.a"        # [unix]
    - test -f "$PREFIX/lib/libcloog-isl.so"       # [linux]
    - test -f "$PREFIX/lib/libcloog-isl.dylib"    # [osx]

about:
  home: http://www.cloog.org/
  license: LGPL 2.1
  license_file: LICENSE
  summary: A free software and library to generate code for scanning Z-polyhedra.

extra:
  recipe-maintainers:
    - jakirkham
