travis:
  secure:
    BINSTAR_TOKEN: jLflPYAJwxLICoFl6Sn5xclsx7zXHpTbILDw8haL445UaCyRX+6TKlqhWf3yP0TKylQWfn9Fr/9T/cNeFSuBfpdqzBoQ+uwdOcIRIYks3MSCSAW7WaE89lqm9ECaQuXUH+THyqbuF+Hnr7o8gaZrH5DPhAywCNOy8dC5fECnw+ZTPUgBy4Kx4dSHqDov/yNkbqI4balxkvuzfEt9mlgzNtwmcjYR8zld8zy83qUanmc8OPZC+8K3UHqDAn+z5sxUtTOAs8lWeIHZSOnPEVqPbqS7BfzBr2iMhh3o4r4VfHb9t1YSSa13p+C1uMnJ+xtQ/ZDHbRyUpeOI0220VUXnrEw83JZai02b88Yqs6s7NyxQPB9eenwORd4XPJWs2pBj+EfTY4/Yn3aXUpEEStaVW6rKnXNQw2+4/d1eZ+aZqyt3a0ClrTZGkU41kBqCViWrgNVwYr5mQr4Ym3MgtfoPXRzjJaSqPF0daBKi0xE7glIgo1dVu5Q8qaw3DbisGOL3z0sffUppKoVQNm+ReG87k81kOwEdJjv+fIJ3vTzooVD8H477oJu0FwP1MUE8S8VMlP7nqaKGdSWwZxCu82md7k5NN6SqIRf5s/2Tz/bHpnAVDft02dkV1P/ThlSyP9vJCX3FZ7v0Hrd43hp4S63FEhtLctVnRfAzltMFZ1g8WUk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
